### ISSUE TITLE
llm.api_key is not found in auto eval

### ISSUE THREAD

**Issue by saakethch** [microsoft/TaskWeaver#27] opened 2023-12-06 11:42 UTC
i have put the key in project and evaluator_config.json
raise ValueError(f"Config value {var_name} is not found")      
ValueError: Config value llm.api_key is not found
**To Reproduce**
Auto eval example run

**Comment by zhangxu0307** [comment] 2023-12-06 12:23
Hi, @saakethch ! Could you please provide more detailed information about the error? We are uncertain whether the issue is caused by the auto_eval configuration or the taskweaver configuration. If possible, kindly share the call stack and error logs with us. Thank you.

**Comment by zhangxu0307** [comment] 2023-12-06 13:32
Have you moved `taskweaver` folder to `auto_eval`? 
`d:\HolonicSpace\space\mmmu\TaskWeaver-main\TaskWeaver-main\auto_eval\taskweaver\config\module_config.py`.
In this case, Taskweaver would not find its config file correctly. You only need to complete the` evalutaion_config.json` file and `taskweaver_config.json` file, then run the evaluation script.

**Comment by saakethch** [comment] 2023-12-07 08:37
I still get the same error: 

taskweaver_eval.py placed in root where the taskweaver source folder exists.

if __name__ == "__main__":
    # run single case
    eval_case_file_path = "auto_eval\cases\init_say_hello.yaml"

outputs error: 
    
    ```
File "d:\HolonicSpace\space\mmmu\TaskWeaver-main\TaskWeaver-main\taskweaver\config\config_mgt.py", line 96, in _get_config_value      
    raise ValueError(f"Config value {var_name} is not found")
ValueError: Config value llm.api_key is not found
```
I have my api key in auto_eval\evaluator_config.json

**Comment by zhangxu0307** [comment] 2023-12-07 10:26
Plz refer to [readme](https://github.com/microsoft/TaskWeaver/blob/main/auto_eval/README.md) file to run the auto evalutaion script. Thanks.

**Comment by zhangxu0307** [comment] 2023-12-07 23:30
> Thanks, That helped.
> 
> Now the auto_eval runs but at the very end I get this : ` AttributeError: module 'openai' has no attribute 'error'`
> 
> I have installed taskweaver in a virtualenv

Could you provide the detailed error logs? Thanks.

**Comment by zhangxu0307** [comment] 2023-12-13 08:23
We will close this issue because of no more updating.

**Closed by zhangxu0307** 2023-12-13 08:23 UTC
